#!/bin/sh
THEMEDIR="$( cd "$( dirname "$0" )" && cd ".." && pwd )"

rm ${THEMEDIR}/basepress/wordpress/wp-content/plugins
rm ${THEMEDIR}/basepress/wordpress/wp-content/themes
rm ${THEMEDIR}/basepress/wordpress/wp-content/junto-content

ln -nfs ${THEMEDIR}/plugins ${THEMEDIR}/basepress/wordpress/wp-content/plugins
ln -nfs ${THEMEDIR}/themes ${THEMEDIR}/basepress/wordpress/wp-content/themes
ln -nfs ${THEMEDIR}/basepress/junto-common/junto-content ${THEMEDIR}/basepress/wordpress/wp-content/junto-content

mkdir ${THEMEDIR}/basepress/wordpress/wp-content/blogs.dir
mkdir ${THEMEDIR}/basepress/wordpress/wp-content/uploads

find ${THEMEDIR}/basepress/lib/php-object-generator/objects -maxdepth 1 -type l -exec unlink {} \;


if [ -d "$DIRECTORY" ]; then
    for filename in ${THEMEDIR}/subthemes/*
    do
        for themedirectory in ${filename}/themes/*
        do
            ln -nfs ${themedirectory} ${THEMEDIR}/themes/$(basename ${themedirectory})
        done;
    done;
fi

#adds the pog objects into the pog folder so that they can be generated by the pog system
for themedirectory in ${THEMEDIR}/themes/*
do
    for pogobject in ${themedirectory}/__models/pog-objects/*.php
    do
        ln -nfs ${pogobject} ${THEMEDIR}/basepress/lib/php-object-generator/objects/$(basename ${pogobject})
    done;
done;

